olxprojectss/api/urls.py
from rest_framework.urls import path
from rest_framework.routers import DefaultRouter
from api import views
from rest_framework.authtoken.views import ObtainAuthToken
#from rest_framework_simplejwt.views import TokenObtainPairView,TokenRefreshView

router=DefaultRouter()
router.register("accounts/users",views.Usercreation,basename="users"),
urlpatterns = [
    path("token/",ObtainAuthToken.as_view())
    # path("token/",TokenObtainPairView.as_view()),
    # path("token/refresh/",TokenRefreshView.as_view())
]+router.urls

olxprojectss/olxprojectss/urls.py
from django.contrib import admin
from django.urls import path,include
from django.conf import settings
from django.conf.urls.static import static

urlpatterns = [
    path('admin/', admin.site.urls),
    path("api/",include("api.urls")),
    path("",include("olxweb.urls")),

]+ static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

olxprojectss/olxweb/urls.py
from django.urls import path
from olxweb import views
from django.conf import settings
from django.conf.urls.static import static


urlpatterns= [
    path("signup",views.Signupview.as_view(),name="register"),
    path("",views.LoginView.as_view(),name="signin"),
    path("home",views.Indexview.as_view(),name="home"),
    path("signout",views.Signoutview.as_view(),name="signout"),
    path("profile/add",views.Userprofilecreateview.as_view(),name="profile-add"),
    path("profile",views.Profiledetailview.as_view(),name="profile-detail"),
    path("profile/<int:id>/change",views.Profileupdateview.as_view(),name="profile-change"),
    path("product/<int:id>",views.ProductDetailView.as_view(),name="product-detail"),
    path("productadd/",views.productAddView.as_view(),name="product-add"),
    path("products/<int:id>/carts/add",views.AddtocartView.as_view(),name="cart-add"),
    path("customer/carts/all",views.CartListView.as_view(),name="cart-list"),
    path("questions/<int:id>/add",views.AddquestionView.as_view(),name="add-question"),
    path("questions/<int:id>/answer/add",views.AddanswerView.as_view(),name="add-answer"),
    path("customer/order/all",views.OrderView.as_view(),name="order-list"),
    path("carts/<int:id>/change",views.CartRemoveview.as_view(),name="cart-change"),







]+ static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

olxprojectss/api/models.py
from django.db import models
from django.contrib.auth.models import User

# Create your models here.

class Category(models.Model):
    category_name=models.CharField(max_length=200)
    is_active=models.BooleanField(default=True)

    def __str__(self):
        return self.category_name

class Products(models.Model):
    product_name=models.CharField(max_length=100)
    category=models.ForeignKey(Category,on_delete=models.CASCADE)
    image=models.ImageField(upload_to="images",null=True)
    description=models.CharField(max_length=300)
    product_details=models.CharField(max_length=400)
    price=models.PositiveIntegerField()
    is_active=models.BooleanField(default=True)

    def __str__(self):
        return self.product_name



class Userprofile(models.Model):
    user=models.OneToOneField(User,on_delete=models.CASCADE,related_name="profile")
    profile_pic=models.ImageField(upload_to="images",null=True)
    address=models.CharField(max_length=300)
    place=models.CharField(max_length=200)
    contact_number=models.PositiveIntegerField()
    is_active=models.BooleanField(default=True)


class Questions(models.Model):
    description=models.CharField(max_length=200)
    product=models.ForeignKey(Products,on_delete=models.CASCADE)
    user=models.ForeignKey(User,on_delete=models.CASCADE,related_name="questions")
    created_date=models.DateTimeField(auto_now_add=True)

    def __str__(self):
        return self.description
    
    class Meta:
        ordering=["-created_date"]

    @property
    def question_answer(self):
        return Questions.objects.filter(questions=self)

class Answers(models.Model):
    questions=models.ForeignKey(Questions,on_delete=models.CASCADE)
    answer=models.CharField(max_length=300)
    user=models.ForeignKey(User,on_delete=models.CASCADE,related_name="answers")
    created_date=models.DateTimeField(auto_now_add=True)

class carts(models.Model):
    user=models.ForeignKey(User,on_delete=models.CASCADE)
    product=models.ForeignKey(Products,on_delete=models.CASCADE,null=True)
    created_date=models.DateTimeField(auto_now_add=True)
    options=(("product added ","product added"),
             ("product removed","product removed"),
    )
    status=models.CharField(max_length=200,choices=options,default="product added")
    qty=models.PositiveIntegerField(default=1)


class Soldoutproducts(models.Model):
    user=models.ForeignKey(User,on_delete=models.CASCADE,related_name="soldout")
    product=models.ForeignKey(Products,on_delete=models.CASCADE)
    created_date=models.DateTimeField(auto_now_add=True)
    options=(
        ("soldout","soldout"),
    )
    status=models.CharField(max_length=200,choices=options,default="soldout")

olxprojectss/olxweb/models.py
from django.db import models

# Create your models here.

olxprojectss/olxweb/forms.py
from django import forms
from django.contrib.auth.models import User
from django.contrib.auth.forms import UserCreationForm
from api.models import Userprofile,Products,Questions

class Registrationform(UserCreationForm):
    password1=forms.CharField(widget=forms.TextInput(attrs={"class":"form-control"}))
    password2=forms.CharField(widget=forms.TextInput(attrs={"class":"form-control"}))

    class Meta:
        model=User
        fields=["first_name","last_name","username","email","password1","password2"]
        widgets={
            "username":forms.TextInput(attrs={"class":"form-control"}),
            "email":forms.EmailInput(attrs={"class":"form-control"}),
            "password":forms.PasswordInput(attrs={"class":"form-control"}),
            "first_name":forms.TextInput(attrs={"class":"form-control"}),
            "last_name":forms.TextInput(attrs={"class":"form-control"})
            }
        
class LoginForm(forms.Form):
    username=forms.CharField(widget=forms.TextInput(attrs={"class":"form-control"}))
    password=forms.CharField(widget=forms.PasswordInput(attrs={"class":"form-control"}))

class UserprofileForm(forms.ModelForm):
    class Meta:
        model=Userprofile
        fields=["profile_pic","address","place","contact_number"]

class ProductForm(forms.ModelForm):
    class Meta:
        model=Products
        fields=["product_name","description","image","price","category"]



class questionForm(forms.ModelForm):
    class Meta:
        model=Questions
        fields=["description"]

olxprojectss/olxweb/views.py
from django.shortcuts import render,redirect
from django.views.generic import CreateView,TemplateView,FormView,View,UpdateView,ListView
from django.contrib.auth.models import User
from olxweb.forms import Registrationform,LoginForm,UserprofileForm,ProductForm
from django.urls import reverse_lazy
from django.contrib.auth import login,authenticate,logout
from django.views.decorators.cache import never_cache
from django.utils.decorators import method_decorator
from django.contrib import messages
from django.contrib.messages.views import SuccessMessageMixin
from api.models import Userprofile,Products,carts,Questions,Answers,Soldoutproducts
# Create your views here.
def sigin_required(fn):
    def wrapper(request,*args,**kwargs):
        if not request.user.is_authenticated:
            return redirect("signin")
        else:
            return fn(request,*args,**kwargs)
    return wrapper
decs=[sigin_required,never_cache]

class Signupview(CreateView):
    form_class=Registrationform
    model=User
    template_name="register.html"
    success_url=reverse_lazy("signin")
    def form_valid(self, form):
        messages.success(self.request, "Account created successfully")
        return super().form_valid(form)
class LoginView(FormView):
    form_class=LoginForm
    template_name="login.html"

    def post(self,request,*args,**kwargs):
        form=LoginForm(request.POST)
        if form.is_valid():
            uname=form.cleaned_data.get("username")
            pwd=form.cleaned_data.get("password")
            usr=authenticate(request,username=uname,password=pwd)
            if usr:
                login(request,usr)
                messages.success(request,"account created seccessfully")
                return redirect("home")
            else:
                messages.error(request,"provided credentials are invalid")
                return render(request,"login.html",{"form":form})

@method_decorator(decs,name='dispatch')
class Indexview(CreateView,ListView):
    model=Products
    form_class=ProductForm
    template_name="index.html"
    success_url=reverse_lazy("home")
    context_object_name="products"

    def form_valid(self, form):
        form.instance.user=self.request.user
        return super().form_valid(form)

class Userprofilecreateview(CreateView):
    model=Userprofile
    form_class=UserprofileForm
    template_name="profile-add.html"
    success_url=reverse_lazy("home")

    def form_valid(self, form):
        form.instance.user=self.request.user
        return super().form_valid(form)
    
class Profiledetailview(View):
    def get(self,request,*args,**kwargs):
        qs=Userprofile.objects.filter(user=request.user,is_active=True)
        return render(request,"profile-details.html",{"profile":qs})

class Profileupdateview(UpdateView):
    model=Userprofile
    template_name="profileupdate.html"
    form_class=UserprofileForm
    success_url=reverse_lazy("home")
    pk_url_kwarg="id"

class productAddView(CreateView):
    model=Products
    form_class=ProductForm
    template_name="product-add.html"
    success_url=reverse_lazy("home")

class ProductDetailView(View):
    def get(self,request,*args,**kwargs):
            id=kwargs.get("id")
            qs=Products.objects.get(id=id)
            return render(request,"product-detail.html",{"product":qs})

class AddtocartView(View):
    def post(self,request,*args,**kwargs):
        qty=request.POST.get("qty")
        user=request.user
        id=kwargs.get("id")
        product=Products.objects.get(id=id)
        carts.objects.create(product=product,user=user,qty=qty)
        return redirect("home")

class CartListView(View):
    def get(self,request,*args,**kwargs):
        qs=carts.objects.filter(user=request.user,status="product added").order_by("-id")
        return render(request,"saved-list.html",{"carts":qs})
    
class CartRemoveview(View):
    def get(self,request,*args,**kwargs):
        id=kwargs.get("id")
        carts.objects.filter(id=id).update(status="cancelled")
        return redirect("home")
    
class AddquestionView(View):
    def post(self,request,*args,**kwargs):
        qid=kwargs.get("id")
        ques=Questions.objects.get(id=qid)
        usr=request.user
        ans=request.POST.get("question")
        Questions.objects.create(user=usr,questions=ques,answer=ans)
        return redirect("home")
    
class AddanswerView(View):
    def post(self,request,*args,**kwargs):
        qid=kwargs.get("id")
        ques=Answers.objects.get(id=qid)
        usr=request.user
        ans=request.POST.get("answer")
        Answers.objects.create(user=usr,questions=ques,answer=ans)
        return redirect("home")
    
class OrderView(View):
    def get(self,request,*args,**kwargs):
        qs=Soldoutproducts.objects.filter(user=request.user)
        return render(request,"order-list.html",{"order":qs})


class Signoutview(View):
    def get(self,request,*args,**kwargs):
        logout(request)
        return redirect("signin")

olxprojectss/olxweb/templates/base.html
<!DOCTYPE html>
{%load static%}
<html lang="en">

<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no" />
    <meta name="description" content="" />
    <meta name="author" content="" />
    <title>Shop Homepage - Start Bootstrap Template</title>
    <!-- Favicon-->
    <link rel="icon" type="image/x-icon" href="{%static 'assets/favicon.ico'%}" />
    <!-- Bootstrap icons-->
    <link href="https://cdn.jsdelivr.net/npm/bootstrap-icons@1.5.0/font/bootstrap-icons.css" rel="stylesheet" />
    <!-- Core theme CSS (includes Bootstrap)-->
    <link href="{%static 'css/styles.css'%}" rel="stylesheet" />
</head>

<body>
    <!-- Navigation-->
    <nav class="navbar navbar-expand-lg navbar-light bg-blue">
        <div class="container px-4 px-lg-5">
            <a class="navbar-brand" href="#!">Welcome <strong>{{request.user}}</strong></a>
            <button class="navbar-toggler" type="button" data-bs-toggle="collapse"
                data-bs-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false"
                aria-label="Toggle navigation"><span class="navbar-toggler-icon"></span></button>
            <div class="collapse navbar-collapse" id="navbarSupportedContent">
                <ul class="navbar-nav me-auto mb-2 mb-lg-0 ms-lg-4">
                    <li class="nav-item"><a class="nav-link active" aria-current="page" href="{%url 'home'%}">Home</a>
                    </li>
                    <li class="nav-item"><a class="nav-link" href="{%url 'order-list'%}">My Products</a></li>
                    <li class="nav-item"><a class="nav-link active" aria-current="page"
                            href="{%url 'product-add'%}">add-product</a></li>
                    {%if request.user.profile%}
                        <li class="nav-item"><a class="nav-link active" aria-current="page" href="{%url 'profile-detail'%}">User Profile</a></li>
                        <li class="nav-item"><a class="nav-link active" aria-current="page" href="{%url 'profile-change' request.user.profile.id%}">Profile Update</a></li>

                    {%else%}
                        <li class="nav-item"><a class="nav-link active" aria-current="page" href="{%url 'profile-add'%}">Add profile</a></li>
                    {%endif%}
                    <li class="nav-item"><a class="nav-link active" aria-current="page"
                            href="{%url 'signout'%}">Logout</a></li>
                </ul>
                <form class="d-flex">
                    <a class="btn btn-outline-dark" href="{%url 'cart-list'%}">
                        <i class="bi-cart-fill me-1"></i>
                        Saved Products
                        <span class="badge bg-dark text-white ms-1 rounded-pill">{{count}}</span>
                    </a>
                </form>
            </div>
        </div>
    </nav>
    <!-- Header-->
    <header class="bg-dark py-5">
        <div class="container px-4 px-lg-5 my-5">
            <div class="text-center text-white">
                <h1 class="display-4 fw-bolder">Olx</h1>
                <p class="lead fw-normal text-white-50 mb-0">tap into your connections</p>
            </div>
        </div>
    </header>
    {%block body%}

    {%endblock%}
    <!-- Footer-->
    <footer class="py-5 bg-dark">
        <div class="container">
            <p class="m-0 text-center text-white">Copyright &copy; Your Website 2022</p>
        </div>
    </footer>
    <!-- Bootstrap core JS-->
    <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.1.3/dist/js/bootstrap.bundle.min.js"></script>
    <!-- Core theme JS-->
    <script src="{%static 'js/scripts.js'%}"></script>
</body>

</html>

olxprojectss/olxweb/templates/index.html

{%extends 'base.html'%}
{%block body%}
<section class="py-5">
    <div class="container px-4 px-lg-5 mt-5">
        <div class="row gx-4 gx-lg-5 row-cols-2 row-cols-md-3 row-cols-xl-4 justify-content-center">
            {%for p in products%}
            <div class="col mb-5">
                <div class="card h-100">
                    <!-- Product image-->
                    {%if p.image%}
                    <img class="card-img-top" src="{{p.image.url}}" alt="..." /height="100%">
                    {%else%}
                    <img class="card-img-top" src="https://dummyimage.com/450x300/dee2e6/6c757d.jpg" alt="..." />


                    {%endif%}
                    <!-- Product details-->
                    <div class="card-body p-4">
                        <div class="text-center">
                            <!-- Product name-->
                            <h5 class="fw-bolder">{{p.product_name}}</h5>
                            <!-- Product price-->
                            Rs{{p.price}}
                        </div>
                    </div>
                    <!-- Product actions-->
                    <div class="card-footer p-4 pt-0 border-top-0 bg-transparent">
                        <div class="text-center"><a class="btn btn-outline-dark mt-auto" href="{%url 'product-detail' p.id%}">View More</a></div>
                    </div>
                </div>
            </div>
            {%endfor%}
        </div>
    </div>
</section>

{%endblock%}

olxprojectss/olxweb/templates/login.html
<!DOCTYPE html>
<html lang="en">
<head>
  <meta charset="UTF-8">
  <meta http-equiv="X-UA-Compatible" content="IE=edge">
  <meta name="viewport" content="width=device-width, initial-scale=1.0">
  <title>Document</title>
  <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.3.0-alpha1/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-GLhlTQ8iRABdZLl6O3oVMWSktQOp6b7In1Zl3/Jr59b6EGGoI1aFkw7cmDA6j6gD" crossorigin="anonymous">
  <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/4.7.0/css/font-awesome.min.css">

</head>
<body>
  {% if messages %}
  {% for message in messages %}
      <div class="text-center alert alert-{{ message.tags }}">
          {{ message|safe }}
      </div>
  {% endfor %}
{% endif %}
  <form action="" method="post">
    {%csrf_token%}
    <section class="vh-100 gradient-custom">
      <div class="container py-5 h-100">
        <div class="row d-flex justify-content-center align-items-center h-100">
          <div class="col-12 col-md-8 col-lg-6 col-xl-5">
            <div class="card bg-dark text-white" style="border-radius: 1rem;">
              <div class="card-body p-5 text-center">
    
                <div class="mb-md-5 mt-md-4 pb-5">
    
                  <h2 class="fw-bold mb-2 text-uppercase">Login</h2>
                  <p class="text-white-50 mb-5">Please enter your login and password!</p>
                  <div class="form-outline form-white mb-4">
                    <label class="form-label" for="typeEmailX">Username</label>
                    <input type="text" id="typeEmailX" class="form-control form-control-lg" name="username" placeholder="username"/>

                  </div>
    
                  <div class="form-outline form-white mb-4">
                    <label class="form-label" for="typePasswordX">Password</label>
                    <input type="password" id="typePasswordX" class="form-control form-control-lg" name="password" placeholder="password" />

                  </div>
    
                  <p class="small mb-5 pb-lg-2"><a class="text-white-50" href="#!">Forgot password?</a></p>
    
                  <button class="btn btn-outline-light btn-lg px-5" type="submit">Login</button>
    
                  <div class="d-flex justify-content-center text-center mt-4 pt-1">
                    <a href="#!" class="text-white"><i class="fa fa-facebook-f fa-lg"></i></a>
                    <a href="#!" class="text-white"><i class="fa fa-twitter fa-lg mx-4 px-2"></i></a>
                    <a href="#!" class="text-white"><i class="fa fa-google fa-lg"></i></a>
                  </div>
    
                </div>
    
                <div>
                  <p class="mb-0">Don't have an account? <a href="{%url 'register'%}" class="text-white-50 fw-bold">Sign Up</a>
                  </p>
                </div>
    
              </div>
            </div>
          </div>
        </div>
      </div>
    </section>
  </form>
</body>
</html>

olxprojectss/olxweb/templates/order-list.html
{%extends 'base.html'%}
{%block body%}

{%for o in order%}
<section class="py-5">
    <div class="container px-4 px-lg-5 my-5">
        <div class="row gx-4 gx-lg-5 align-items-center">
            <div class="col-md-4">
                {%if o.product.image%}
                <img class="card-img-top mb-5 mb-md-0" src="{{o.product.image.url}}" alt="..." / height="500px">
                {%else%}
                <img class="card-img-top mb-5 mb-md-0" src="https://dummyimage.com/600x700/dee2e6/6c757d.jpg" alt="..." / height="500px" >
                {%endif%}
            </div>
            <div class="col-md-4">
                <div class="small mb-1"></div>
                <h1 class="display-5 fw-bolder">{{o.product.product_name}}</h1>
                <div class="fs-5 mb-5">
                    <span class="text-decoration-line-through"></span>
                    <span>RS{{o.product.price}}</span>

                    
             
                </div>
            </div>
            <div class="col-4">
                        
                </div> 

        </div>
    </div>
</section>

{%endfor%}

{%endblock%}

olxprojectss/olxweb/templates/product-add.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Document</title>
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.3.0-alpha1/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-GLhlTQ8iRABdZLl6O3oVMWSktQOp6b7In1Zl3/Jr59b6EGGoI1aFkw7cmDA6j6gD" crossorigin="anonymous">

</head>
<body>
    <div class="container p-5 border shadow mt-5">
        <div class="row">
            <div class="col-2"></div>
            <div class="col-8">
                <div class="w3-row-padding">
                    <div class="w3-col m12">
                      <div class="w3-card w3-round w3-white">
                        <div class="w3-container w3-padding">
                          <h2 class="w3-opacity" class="text-center mt-5">Add Products</h2>
                          <form action="" method="post" enctype="multipart/form-data">
                            {%csrf_token%}
                            <p>
                              <label for="id_product_name">Product name:</label>
                              <input type="text" name="product_name" maxlength="100" required="" id="id_product_name" class="form-control">
                              
                              
                            </p>
                            <p>
                              <label for="id_description">Description:</label>
                              <input type="text" name="description" maxlength="300" required="" id="id_description" class="form-control">
                              
                              
                            </p>
                            <p>
                              <label for="id_image">Image:</label>
                              <input type="file" name="image" accept="image/*" required="" id="id_image" class="form-control">
                              
                              
                            </p>
                            <p>
                              <label for="id_price">Price:</label>
                              <input type="number" name="price" min="0" required="" id="id_price" class="form-control">
                              
                              
                            </p>
                            <p>
                              <label for="id_category">Category:</label>
                              <select name="category" required="" id="id_category" class="form-control">
                            <option value="" selected="">---------</option>
                          
                            <option value="1">electronics</option>
                          
                            <option value="2">cars</option>
                          
                            <option value="3">bikes</option>
                          
                          </select>
                              
                              
                                
                              
                            </p>
                           <button type="submit" class="btn btn-outline-success form-control"><i class="fa fa-pencil"></i>  Add Product</button> 
            
                          </form>
                        </div>
                      </div>
                    </div>
                  </div>
            </div>
            <div class="col-2">
            </div>
        </div>
    </div>
</body>
</html>

olxprojectss/olxweb/templates/product-detail.html
{%extends 'base.html'%}
{%block body%}
<section class="py-5">
    <div class="container px-4 px-lg-5 my-5">
        <div class="row gx-4 gx-lg-5 align-items-center">
            <div class="col-md-4">
                {%if product.image%}
                <img class="card-img-top mb-5 mb-md-0" src="{{product.image.url}}" alt="..." />
                {%else%}
                <img class="card-img-top mb-5 mb-md-0" src="https://dummyimage.com/600x700/dee2e6/6c757d.jpg"
                    alt="..." />
                {%endif%}
            </div>
            <div class="col-md-4">
                <div class="small mb-1"></div>
                <h1 class="display-5 fw-bolder">{{product.product_name}}</h1>
                <div class="fs-5 mb-5">
                    <span class="text-decoration-line-through"></span>
                    <span>RS{{product.price}}</span>
                </div>
                <p class="lead">{{product.description}}</p>
                <div class="d-flex">
                    <form action="{%url 'cart-add' product.id%}" method="post">
                        {%csrf_token%}
                        <input class="form-control text-center me-3" id="inputQuantity" type="num" value="1"
                            style="max-width: 3rem" name="qty" />
                        <button class="btn btn-outline-dark flex-shrink-0 mt-4" type="submit">
                            <i class="bi-cart-fill me-1"></i>
                            Add to Saved Products
                        </button>
                    </form>
                </div>
            </div>
            <div class="col-md-4 p-5 border shadow">
                <div>
                    <h3>Ask about product</h3>
                    <form action="" method="post" class="mt-3">
                        {%csrf_token%}
                        <input type="text" name="answer" placeholder="enter your answer" class="form-control">
                        <button type="submit" class="form-control mt-4 btn btn-outline-success">add</button>

                    </form>
                </div>
            </div col-nd-4>
            {%for q in questions%}
            <div class="w3-container w3-card w3-white w3-round w3-margin"><br>
                {%if q.user.profile.profile_pic%}
                <img src="{{q.user.profile.profile_pic.url}}" alt="Avatar" class="w3-left w3-circle w3-margin-right"
                    style="width:70px" height="80px">
                {%else%}
                <img src="/w3images/avatar2.png" alt="Avatar" class="w3-left w3-circle w3-margin-right"
                    style="width:60px">
                {%endif%}
                    {{q.created_date}}</span>
                <h4>{{q.user}}</h4><br>
                <hr class="w3-clear">
                <p>{{q.description}}</p>
                </div>
                <div class="section">
                    <div class="card mb-3" style="max-width: 500pxx;">
                        <div class="row g-0">
                            <div class="col-md-2">
                                {%if request.user.profile.profile_pic%}
                                <img src="{{request.user.profile.profile_pic.url}}" alt="Avatar"
                                    class="w3-left w3-circle w3-margin-right" style="width: 70px" height="80px">
                                {%else%}
                                <img src="/w3images/avatar2.png" alt="Avatar" class="w3-left w3-circle w3-margin-right"
                                    style="width:60px">
                                {%endif%}
                            </div>
                            <div class="col-md-10">
                                <div class="card-body">
                                    <p class="card-text">
                                    <form action="{%url 'add-answer' q.id%}" method="post">
                                        {%csrf_token%}
                                        <input type="text" name="answer" class="form-control rounded-pill"
                                            placeholder="add your ansewer">
                                        <button type="submit"
                                            class="w3-button w3-theme-d2 w3-margin-bottom mt-2 btn btn-outline-btn-success"><i></i>Add</button>

                                    </form>
                                    </p>
                                </div>
                            </div>
                        </div>
                    </div>
                </div>
            </div>
            {%endfor%}

            <div class="col-4 mr-6">

            </div>

        </div>
    </div>
</section>
{%endblock%}

olxprojectss/olxweb/templates/saved-list.html
{%extends 'base.html'%}
{%block body%}

{%for c in carts%}
<section class="py-5">
    <div class="container px-4 px-lg-5 my-5">
        <div class="row gx-4 gx-lg-5 align-items-center">
            <div class="col-md-4">
                {%if c.product.image%}
                <img class="card-img-top mb-5 mb-md-0" src="{{c.product.image.url}}" alt="..." / height="500px">
                {%else%}
                <img class="card-img-top mb-5 mb-md-0" src="https://dummyimage.com/600x700/dee2e6/6c757d.jpg" alt="..."
                    / height="500px">
                {%endif%}
            </div>
            <div class="col-md-4">
                <div class="small mb-1"></div>
                <h1 class="display-5 fw-bolder">{{c.product.product_name}}</h1>
                <div class="fs-5 mb-5">
                    <span class="text-decoration-line-through"></span>
                    <span>RS{{c.product.price}}</span>
                    <span>status {{c.status}}</span>

                </div>
            </div>
            <div class="col-4">

                <a href="{%url 'cart-change' c.id%}" class="btn btn-danger">cancel Order</a>
            </div>

        </div>
    </div>
</section>

{%endfor%}

{%endblock%}